### ISSUE TITLE
Getting 500 Error

### ISSUE THREAD

**Issue by alimirshad** [paypaldev/node-samples#2]
Hello, 

I am trying to process payment using the following code. but always getting 500 error. I have searched and found that this can be because of the overused card. I have generated a new card but the problem is the same. Please suggest what is the problem. 

`var create_card_details = {
"type": "visa",
"number": "4311196893073140",
"expire_month": "09",
"expire_year": "2023",
"first_name": "John",
"last_name": "Doe",
"payer_id": uuid.v4()
};

paypal.credit_card.create(create_card_details, function(error, credit_card){
if(error){
console.error("here "+error);
} else {
console.log("Card Created");
console.log(credit_card.id);
console.log(credit_card.payer_id);

var card_data = {
"intent": "sale",
"payer": {
"payment_method": "credit_card",
"funding_instruments": [{
"credit_card_token": {
"credit_card_id": credit_card.id,
"payer_id": credit_card.payer_id
}
}]
},
"transactions": [{
"amount": {
"total": "7.47",
"currency": "USD",
"details": {
"subtotal": "7.41",
"tax": "0.03",
"shipping": "0.03"
}
},
"description": "This is the payment transaction description." 
}]
};
paypal.payment.create(card_data, function(error, payment){
if(error){
res.json({error:true,message:error})
} else {
res.json({card:payment})

}
});
}
});`

**Comment by aly-irshad** [comment]
Not able to see logs on PayPal and not getting any debug id in response

**Comment by monti-star** [comment]
Closing this issue as this repo is on a path to being archived.
